### ISSUE TITLE
SearchCritieria not working in vsts-rest-api-specs/specification/tfvc/4.1/

### ISSUE THREAD

**Issue by Imroath** [MicrosoftDocs/vsts-rest-api-specs#87]
We work on TFS 2018.2. 
Get Changesets with searchCriteria does not work correctly - meaning filters are not applied. Meaning this will not work correctly:
https://X/tfs/Darwin/_apis/tfvc/changesets?api-version=4.1&searchCriteria.fromDate=2018-09-14T02%3A00%3A00.000Z
But this will:
https://X/tfs/Darwin/_apis/tfvc/changesets?api-version=4.1&fromDate=2018-09-14T02%3A00%3A00.000Z

Also, 3 examples:
https://docs.microsoft.com/en-us/rest/api/vsts/tfvc/changesets/get%20changesets?view=vsts-rest-4.1#get_the_changesets_for_a_range_of_changeset_ids.
https://docs.microsoft.com/en-us/rest/api/vsts/tfvc/changesets/get%20changesets?view=vsts-rest-4.1#get_the_changesets_for_a_range_of_dates.
https://docs.microsoft.com/en-us/rest/api/vsts/tfvc/changesets/get%20changesets?view=vsts-rest-4.1#get_the_changesets_ordering_by_id_ascending.

all have the same GET sample request: GET https://dev.azure.com/{organization}/_apis/tfvc/changesets?api-version=4.1
Which is simply wrong. There should be either 3 different GET queries or POST actions with example JSON files

**Comment by joebourneMS** [comment]
Hello Imroath, I am picking up this issue to get to the bottom of the searchCriteria issue. We'll also get the sample GET requests cleaned up. Hang tight while we investigate the searchCriteria issue.

**Comment by wnjenkin** [comment]
@Imroath this issue has been resolved. closing the issue

**Comment by Tarun60** [comment]
This is not fixed. The API call does not work with the "searchCriteria." prefix.

**Comment by MalloyO** [comment]
@Tarun60 Could you be more specific?

I just tested both with and without "searchCriteria." on TFS 2018.2 and both of these URLs work correctly.  

http://hostname:8080/tfs/DefaultCollection/_apis/tfvc/changesets?api-version=4.1&fromDate=2019-06-24T20:00:00.000Z

http://hostname:8080/tfs/DefaultCollection/_apis/tfvc/changesets?api-version=4.1&searchCriteria.fromDate=2019-06-24T17:00:00.000Z

**Comment by kevinmcp-MSFT** [comment]
@Tarun60 Could you be more specific?

I just tested both with and without "searchCriteria." on TFS 2018.2 and both of these URLs work correctly.

http://hostname:8080/tfs/DefaultCollection/_apis/tfvc/changesets?api-version=4.1&fromDate=2019-06-24T20:00:00.000Z

http://hostname:8080/tfs/DefaultCollection/_apis/tfvc/changesets?api-version=4.1&searchCriteria.fromDate=2019-06-24T17:00:00.000Z

**Comment by Tarun60** [comment]
I was trying with searchCriteria.$top

This is did not work – it returned all the records:  http://hostname:8080/tfs/DefaultCollection/project/_apis/git/repositories/name/commits?searchCriteria.$top=2&api-version=4.1<%20http:/hostname:8080/tfs/DefaultCollection/project/_apis/git/repositories/name/commits?searchCriteria.$top=2&api-version=4.1>

This worked:  http://hostname:8080/tfs/DefaultCollection/project/_apis/git/repositories/name/commits?$top=2&api-version=4.1<%20http:/hostname:8080/tfs/DefaultCollection/project/_apis/git/repositories/name/commits?$top=2&api-version=4.1>

Regards,
Tarun

**Comment by kevinmcp-MSFT** [comment]
Hi Tarun,

This thread was regarding TFVC REST, not Git REST.

That aside, the documentation for 4.1 Get Commits lists $top as the parameter.  This would be correct for TFS 2018 U2 as it should be version 4.1.

[Git Get Commits 4.1](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/commits/get%20commits?view=azure-devops-rest-4.1)

The documentation for Get Commits 5.0+ lists searchCriteria.$top as the parameter.  However it also states that searchCriteria is optional.  
_"Parameters that use the searchCriteria prefix in their name can be specified without it as query parameters, e.g. searchCriteria.$top -> $top"_

[Git Get Commits REST 5.0](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/commits/get%20commits?view=azure-devops-rest-5.0)
[Git Get Commits REST 5.1](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/commits/get%20commits?view=azure-devops-rest-5.1)

Kevin

**Comment by Tarun60** [comment]
Thanks for the response.
Git Get Commits 4.1<https://docs.microsoft.com/en-us/rest/api/azure/devops/git/commits/get%20commits?view=azure-devops-rest-4.1> lists both $top(it does not have any description at that) and searchCriteria.$top – so maybe that needs to be corrected.

Regards,
Tarun

**Comment by kevinmcp-MSFT** [comment]
You are correct.  I missed that the 4.1 doc had them both.  I'll drop a low pri bug into the system to get it corrected.

We generate our REST docs from the actual code, so I'm wondering if the searchCriteria.$top was in process of being implemented when we cut the TFS 2018 bits.  It may need to be decorated to stop showing up in the doc generation because it definitely doesn't work.

Thanks,

Kevin
